name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Pushes to another repository
      id: push_directory
      uses: Practice-Denv/SampleApp@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'Practive-Denv/SampleApp'
        destination-github-username: 'm3c0d322'
        destination-repository-name: 'Practice-Prod/SampleAPp'
        user-email: fsalonga.it.dof@gmail.com
        commit-message: See ORIGIN_COMMIT from $GITHUB_REF
        target-branch: main
    - name: Test get variable exported by push-to-another-repository
      run: echo $DESTINATION_CLONED_DIRECTORY
